# Aktywacja Strategii Odbicie Ogórkowe
Ten notatnik sĹ‚uĹĽy do testowania, wizualizacji i optymalizacji strategii powrotu do Ĺ›redniej po mocnych spadkach.

## Importy, dane i sygnały

In [1]:
import os
import sys

# Dodajemy folder glowny do path aby moduly dzialaly
sys.path.append(os.path.abspath('c:/Users/PC/Documents/Antigravity/lyse-lby'))
os.chdir('c:/Users/PC/Documents/Antigravity/lyse-lby')

import optuna
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

# Importujemy ladowanie danych i nasze nowe moduly
from core.ladowanie_danych import create_stock_dfs
from odbicie.mackowe_sygnaly import mackowe_sygnaly
from odbicie.strategie.odbicie import generate_odbicie_entries
from odbicie.odbicie_atr import generate_odbicie_atr_entries
from odbicie.odbicie_bb import generate_odbicie_bb_entries
from odbicie.tbm.tbm import moving_triple_barrier_labels
from odbicie.optymalizacja import optimize_atr_tbm, optimize_bb_tbm

# Katalog na pliki cache - zawsze wewnatrz odbicie/dane/, niezalezny od cwd
# __vsc_ipynb_file__ dostepny w VS Code; fallback na abspath('')
_SCRIPT_DIR = os.path.dirname(os.path.abspath(globals()["__vsc_ipynb_file__"])) if "__vsc_ipynb_file__" in globals() else os.path.abspath("")
# Jesli notebook lezy wewnatrz odbicie/, katalog jest katalogiem rodzica
if os.path.basename(_SCRIPT_DIR) != 'odbicie':
    _SCRIPT_DIR = os.path.join(_SCRIPT_DIR, 'odbicie')
DANE_DIR = os.path.join(_SCRIPT_DIR, 'cache')
os.makedirs(DANE_DIR, exist_ok=True)
print(f"Cache dir: {DANE_DIR}")

# Ustawienia ladowania danych
import json
with open(os.path.join(_SCRIPT_DIR, 'settings.json'), 'r') as f:
    all_settings = json.load(f)

# Ustawienia ladowania danych
settings = all_settings['data_settings']

Cache dir: c:\Users\PC\Documents\Antigravity\lyse-lby\odbicie\cache

In [2]:
# 1. Ladowanie Danych
import pickle

market = settings.get('market', 'all')
data_cache_file = os.path.join(DANE_DIR, f'dfs_cache_{market}.pkl')

if os.path.exists(data_cache_file):
    print("Znaleziono zapisane dane. Wczytywanie z pliku...")
    with open(data_cache_file, "rb") as f:
        dfs_1d, dfs_1w = pickle.load(f)
    print(f"Wczytano {len(dfs_1d)} symboli 1D i {len(dfs_1w)} symboli 1W z pliku {data_cache_file}.")
else:
    print("Ladowanie danych dziennych i tygodniowych...")
    dfs_1d, dfs_1w = create_stock_dfs(settings)
    print(f"Zaladowano {len(dfs_1d)} symboli 1D i {len(dfs_1w)} symboli 1W.")
    print("Zapisywanie danych do pliku...")
    with open(data_cache_file, "wb") as f:
        pickle.dump((dfs_1d, dfs_1w), f)
    print("Dane zapisane pomyslnie.")

Znaleziono zapisane dane. Wczytywanie z pliku...
Wczytano 478 symboli 1D i 478 symboli 1W z pliku c:\Users\PC\Documents\Antigravity\lyse-lby\odbicie\cache\dfs_cache_sp500.pkl.

In [3]:
# 2. Generowanie Sygnalow Bazowych (mackowe_sygnaly)
market = settings.get('market', 'all')
signals_cache_file = os.path.join(DANE_DIR, f'signals_cache_{market}.pkl')

if os.path.exists(signals_cache_file):
    print("Znaleziono zapisane sygnaly. Wczytywanie z pliku...")
    with open(signals_cache_file, "rb") as f:
        signals_df = pickle.load(f)
    print(f"Wczytano {len(signals_df)} sygnalow z pliku {signals_cache_file}.")
else:
    signals_df = mackowe_sygnaly(
        dfs=dfs_1w,
        settings=settings,
        require_vol_confirmation=True,
        require_cmo_confirmation=True,
        interval='1w',
        entry_offset=0,
        pattern_cols=['hammer', 'inverted_hammer', 'engulfing_bull', 'piercing_line'],
        debug=True
    )
    print("Zapisywanie sygnalow do pliku...")
    with open(signals_cache_file, "wb") as f:
        pickle.dump(signals_df, f)
    print("Sygnaly zapisane pomyslnie.")

signals_df.describe()

Znaleziono zapisane sygnaly. Wczytywanie z pliku...
Wczytano 912 sygnalow z pliku c:\Users\PC\Documents\Antigravity\lyse-lby\odbicie\cache\signals_cache_sp500.pkl.

                      signal_time                  entry_time  signal_close
count                         912                         912    912.000000
mean   2023-10-08 09:01:34.736842  2023-10-08 09:01:34.736842    129.103488
min           2021-07-25 00:00:00         2021-07-25 00:00:00      7.970000
25%           2022-05-15 00:00:00         2022-05-15 00:00:00     51.740002
50%           2023-10-08 00:00:00         2023-10-08 00:00:00     97.340000
75%           2025-03-16 00:00:00         2025-03-16 00:00:00    179.127495
max           2026-02-22 00:00:00         2026-02-22 00:00:00    565.369995
std                           NaN                         NaN    103.256636

## Wejście i Wyjście

In [4]:
# 3. Wybor Strategii Wejscia
# Zmien ta zmienna aby przełaczyc strategie: 'base', 'atr', 'bb'
STRATEGY = 'bb'

strat_settings = all_settings['strategies'][STRATEGY]['entry_settings']
tbm_settings = all_settings['strategies'][STRATEGY]['tbm_settings']

if STRATEGY == 'base':
    # --- Strategia bazowa: staly prog procentowy ---
    threshold_pct = strat_settings['threshold_pct']
    max_hold = strat_settings['max_setup_hold_bars']
    entries_df = generate_odbicie_entries(
        signals_df=signals_df,
        market_data_daily=dfs_1d,
        threshold_pct=threshold_pct,
        enter_on_close=strat_settings.get('enter_on_close', False),
        max_setup_hold_bars=max_hold
    )
    print(f"[base] Wygenerowano {len(entries_df)} wejsc przy progu {threshold_pct*100}%")

elif STRATEGY == 'atr':
    # --- Strategia ATR: prog oparty na wielokrotnosci ATR ---
    atr_period = strat_settings['atr_period']
    atr_factor = strat_settings['atr_factor']
    max_hold = strat_settings['max_setup_hold_bars']
    entries_df = generate_odbicie_atr_entries(
        signals_df=signals_df,
        market_data_daily=dfs_1d,
        atr_period=atr_period,
        atr_factor=atr_factor,
        enter_on_close=strat_settings.get('enter_on_close', False),
        max_setup_hold_bars=max_hold
    )
    print(f"[atr] Wygenerowano {len(entries_df)} wejsc (period={atr_period}, factor={atr_factor})")

elif STRATEGY == 'bb':
    # --- Strategia BB: wejscie przy dotknięciu dolnej wstegi Bollingera ---
    bb_period = strat_settings['bb_period']
    bb_std   = strat_settings['bb_std']
    max_hold = strat_settings['max_setup_hold_bars']
    entries_df = generate_odbicie_bb_entries(
        signals_df=signals_df,
        market_data_daily=dfs_1d,
        bb_period=bb_period,
        bb_std=bb_std,
        enter_on_close=strat_settings.get('enter_on_close', False),
        max_setup_hold_bars=max_hold
    )
    print(f"[bb] Wygenerowano {len(entries_df)} wejsc (period={bb_period}, std={bb_std})")

else:
    raise ValueError(f"Nieznana strategia: '{STRATEGY}'. Uzyj 'base', 'atr' lub 'bb'.")

entries_df.head()

[bb] Wygenerowano 239 wejsc (period=7, std=2.3)

,symbol,signal_time,pattern,entry_time,entry_price,signal_close,bb_period,bb_std,bb_lower,bb_middle,bb_upper,bb_bandwidth,rsi_at_entry,entry_atr,setup_bars
0,AOS,2022-02-06,inverted_hammer,2022-02-10,72.230003,73.580002,7,2.3,71.983393,73.971429,75.959465,0.053751,31.043324,2.154285,4
1,ACN,2025-04-13,inverted_hammer,2025-04-21,279.230011,284.339996,7,2.3,277.337949,284.975717,292.613484,0.053603,33.142228,10.259332,5
2,AES,2023-03-19,inverted_hammer,2023-03-24,22.209999,22.389999,7,2.3,21.545910,22.522857,23.499803,0.086752,31.657501,0.718662,5
3,A,2023-03-19,inverted_hammer,2023-03-23,131.130005,133.179993,7,2.3,129.964181,134.348570,138.732958,0.065269,35.100758,3.829334,4
4,ALB,2023-10-29,inverted_hammer,2023-10-30,127.410004,134.440002,7,2.3,126.938879,135.225717,143.512555,0.122563,26.233313,7.198791,1

In [5]:
# 4. Wyjście z użyciem Moving Triple Barrier Method
trades_df = moving_triple_barrier_labels(
    entries_df=entries_df,
    market_data_daily=dfs_1d,
    tp_mult=tbm_settings['tp_mult'],
    sl_mult=tbm_settings['sl_mult'],
    tp_trail_mult=tbm_settings['tp_trail_mult'],
    max_holding_bars=tbm_settings['max_holding_bars'],
    time_decay_sl=tbm_settings['time_decay_sl'],
    time_decay_mult=tbm_settings.get('time_decay_mult', 1.0),
    active_trailing_sl=tbm_settings['active_trail_sl'],
    sl_trail_mult=tbm_settings['sl_trail_mult'],
    exit_on_close=tbm_settings.get('exit_on_close', True)
)
print(f"Zakończono {len(trades_df)} transakcji.")
trades_df.head()

Zakończono 239 transakcji.

,symbol,signal_time,pattern,entry_time,entry_price,signal_close,bb_period,bb_std,bb_lower,bb_middle,...,entry_atr,setup_bars,exit_time,exit_price,return_pct,exit_reason,hold_bars,current_sl,current_tp_stop,is_tp_trailing
0,AOS,2022-02-06,inverted_hammer,2022-02-10,72.230003,73.580002,7,2.3,71.983393,73.971429,...,2.154285,4,2022-02-23,67.889999,-6.008589,TRAILING_SL,8,NaN,NaN,NaN
1,ACN,2025-04-13,inverted_hammer,2025-04-21,279.230011,284.339996,7,2.3,277.337949,284.975717,...,10.259332,5,2025-05-06,303.799988,8.799189,TRAILING_TP,11,NaN,NaN,NaN
2,AES,2023-03-19,inverted_hammer,2023-03-24,22.209999,22.389999,7,2.3,21.545910,22.522857,...,0.718662,5,2023-04-03,23.820000,7.248990,TRAILING_TP,6,NaN,NaN,NaN
3,A,2023-03-19,inverted_hammer,2023-03-23,131.130005,133.179993,7,2.3,129.964181,134.348570,...,3.829334,4,2023-04-05,138.089996,5.307703,TRAILING_TP,9,NaN,NaN,NaN
4,ALB,2023-10-29,inverted_hammer,2023-10-30,127.410004,134.440002,7,2.3,126.938879,135.225717,...,7.198791,1,2023-11-09,114.599998,-10.054160,TRAILING_SL,8,NaN,NaN,NaN

## Analiza

In [6]:
# 5. Analiza i Statystyki
if not trades_df.empty:
    wins = (trades_df['return_pct'] > 0).sum()
    losses = (trades_df['return_pct'] <= 0).sum()
    win_rate = wins / len(trades_df) * 100
    trades_df['return_per_bar'] = trades_df['return_pct'] / trades_df['hold_bars']

    print(f"Total Trades: {len(trades_df)}")
    print(f"Win Rate: {win_rate:.2f}%")
    print(f"Avg Return: {trades_df['return_pct'].mean():.2f}%")
    print(f"Avg bars held: {trades_df['hold_bars'].mean():.2f}")
    print(f"Avg Return per Bar: {trades_df['return_per_bar'].mean():.2f}%")


    # Powody wyjĹ›cia
    print("\nExit Reasons:")
    print(trades_df['exit_reason'].value_counts())
else:
    print("Brak transakcji do analizy.")

Total Trades: 239
Win Rate: 64.02%
Avg Return: 3.51%
Avg bars held: 9.10
Avg Return per Bar: 0.36%

Exit Reasons:
exit_reason
TRAILING_TP    130
TRAILING_SL     79
TIME_EXIT       27
OPEN             2
SL               1
Name: count, dtype: int64

In [7]:
temp = pd.DataFrame({
    'count': trades_df.groupby('exit_reason').return_pct.count(),
    'avg_return': trades_df.groupby('exit_reason').return_pct.mean(),
    'avg per Bar': trades_df.groupby('exit_reason').return_per_bar.mean(),
    'std per Bar': trades_df.groupby('exit_reason').return_per_bar.std(),
    'cumulativ_return': trades_df.groupby('exit_reason').return_pct.sum(),
    'std': trades_df.groupby('exit_reason').return_pct.std(),
    'avg_hold_bars': trades_df.groupby('exit_reason').hold_bars.mean(),
    'std_hold_bars': trades_df.groupby('exit_reason').hold_bars.std(),
    })

temp

,count,avg_return,avg per Bar,std per Bar,cumulativ_return,std,avg_hold_bars,std_hold_bars
exit_reason,,,,,,,,
OPEN,0,NaN,NaN,NaN,0.000000,NaN,5.500000,0.707107
SL,1,-17.052492,-17.052492,NaN,-17.052492,NaN,1.000000,NaN
TIME_EXIT,27,5.001070,0.333405,0.444508,135.028899,6.667617,15.000000,0.000000
TRAILING_SL,79,-5.261538,-0.855113,0.867418,-415.661482,3.216192,9.037975,3.538952
TRAILING_TP,130,8.688370,1.241689,0.981760,1129.488069,6.489339,8.038462,3.068732

## Ploty

In [8]:
# 6. Interaktywna Wizualizacja Transakcji
from odbicie.plot import show_trade_viewer
import ipywidgets as widgets
from IPython.display import display, clear_output

# Inicjalny rysunek
show_trade_viewer(
    trades_df,
    dfs_1d,
    tp_mult=tbm_settings['tp_mult'],
    sl_mult=tbm_settings['sl_mult'],
    ttp_mult=tbm_settings['tp_trail_mult'],
    max_holding_bars=tbm_settings['max_holding_bars'],
    exit_reason='All',
    active_trailing_sl=tbm_settings['active_trail_sl'],
    sl_trail_mult=tbm_settings['sl_trail_mult'],
    time_decay_sl=tbm_settings['time_decay_sl'],
    time_decay_mult=tbm_settings.get('time_decay_mult', 1.0),
    exit_on_close=tbm_settings.get('exit_on_close', True),
    strategy_type="tbm"
)

HBox(children=(Dropdown(description='Exit Reason:', options=('All', 'SL', 'TIME_EXIT', 'TRAILING_SL', 'TRAILIN…

Output()

## Optymalizacja

### Optuna => BB

In [ ]:
def objective_bb_tbm_direct(trial):
    # Optymalizacja Parametrow BB
    bb_period = trial.suggest_int("bb_period", 5, 20)
    bb_std = trial.suggest_float("bb_std", 1.0, 4.0, step=0.1)
    max_setup_hold_bars = trial.suggest_int("max_setup_hold_bars", 5, 15)

    # Optymalizacja Wyjsc (TBM)
    tp_mult = trial.suggest_float("tp_mult", 0.2, 2.0, step=0.2)
    sl_mult = trial.suggest_float("sl_mult", 0.6, 3.0, step=0.2)
    tp_trail_mult = trial.suggest_float("tp_trail_mult", 0.01, 0.2, step=0.01)
    sl_trail_mult = trial.suggest_float("sl_trail_mult", 0.5, 5.0)
    time_decay_sl = trial.suggest_categorical("time_decay_sl", [True, False])
    time_decay_mult = trial.suggest_float("time_decay_mult", 0.5, 3.0)
    active_trailing_sl =  trial.suggest_categorical("trailing_sl", [True, False])
    max_holding_bars = trial.suggest_int("max_holding_bars", 5, 20)

    bb_tbm_settings = all_settings['strategies']['bb']['tbm_settings']

    # 1. Generowanie wejsc
    entries_df = generate_odbicie_bb_entries(
        signals_df=signals_df,
        market_data_daily=dfs_1d,
        bb_period=bb_period,
        bb_std=bb_std,
        enter_on_close=strat_settings.get('enter_on_close', False),
        rsi_period=14,
        max_setup_hold_bars=max_setup_hold_bars,
    )

    if entries_df.empty or len(entries_df) < 10:
        return 0.0

    # 2. Ewaluacja TBM
    trds = moving_triple_barrier_labels(
        entries_df=entries_df,
        market_data_daily=dfs_1d,
        tp_mult=tp_mult,
        sl_mult=sl_mult,
        tp_trail_mult=tp_trail_mult,
        max_holding_bars=max_holding_bars,
        time_decay_sl=time_decay_sl,
        time_decay_mult=time_decay_mult,
        active_trailing_sl=active_trailing_sl,
        sl_trail_mult=sl_trail_mult,
        exit_on_close=bb_tbm_settings.get('exit_on_close', True)
    )

    if len(trds) < 10:
        return 0.0

    avg_hold_bars = trds['hold_bars'].mean()
    if avg_hold_bars == 0:
        return 0.0

    avg_return = trds['return_pct'].mean()
    return avg_return / avg_hold_bars  # return_per_bar


'''
study_bb_tbm_direct = optuna.create_study(direction="maximize")
study_bb_tbm_direct.optimize(objective_bb_tbm_direct, n_trials=50)

print("Best parameters:", study_bb_tbm_direct.best_params)
print("Best value:", study_bb_tbm_direct.best_value)
'''

[I 2026-03-28 21:41:12,690] A new study created in memory with name: no-name-8e5dd7a9-aeef-48fe-9c23-a9fea0a2bd42
[I 2026-03-28 21:41:18,343] Trial 0 finished with value: -0.03574365670491159 and parameters: {'bb_period': 15, 'bb_std': 2.1, 'max_setup_hold_bars': 15, 'tp_mult': 0.6000000000000001, 'sl_mult': 1.4, 'tp_trail_mult': 0.2, 'sl_trail_mult': 2.8096203823053623, 'time_decay_sl': False, 'time_decay_mult': 2.4981260472718265, 'trailing_sl': False, 'max_holding_bars': 15}. Best is trial 0 with value: -0.03574365670491159.
[I 2026-03-28 21:41:24,423] Trial 1 finished with value: 0.12648941001202754 and parameters: {'bb_period': 7, 'bb_std': 2.4000000000000004, 'max_setup_hold_bars': 15, 'tp_mult': 0.6000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.04, 'sl_trail_mult': 3.8810130930395212, 'time_decay_sl': False, 'time_decay_mult': 1.2985299794649434, 'trailing_sl': True, 'max_holding_bars': 18}. Best is trial 1 with value: 0.12648941001202754.
[I 2026-03-28 21:41:30,341] Trial 2 finished with value: 0.04621031150823459 and parameters: {'bb_period': 5, 'bb_std': 4.0, 'max_setup_hold_bars': 15, 'tp_mult': 0.8, 'sl_mult': 0.6, 'tp_trail_mult': 0.02, 'sl_trail_mult': 2.259967925952787, 'time_decay_sl': True, 'time_decay_mult': 2.4990038384623134, 'trailing_sl': False, 'max_holding_bars': 7}. Best is trial 1 with value: 0.12648941001202754.
[I 2026-03-28 21:41:35,049] Trial 3 finished with value: 0.06397090161544874 and parameters: {'bb_period': 12, 'bb_std': 2.1, 'max_setup_hold_bars': 6, 'tp_mult': 1.2, 'sl_mult': 1.4, 'tp_trail_mult': 0.04, 'sl_trail_mult': 4.196271156861496, 'time_decay_sl': False, 'time_decay_mult': 1.9937828304615943, 'trailing_sl': False, 'max_holding_bars': 16}. Best is trial 1 with value: 0.12648941001202754.
[I 2026-03-28 21:41:41,415] Trial 4 finished with value: 0.10516010834838714 and parameters: {'bb_period': 10, 'bb_std': 1.1, 'max_setup_hold_bars': 12, 'tp_mult': 0.4, 'sl_mult': 1.6, 'tp_trail_mult': 0.18000000000000002, 'sl_trail_mult': 0.8131559234354708, 'time_decay_sl': True, 'time_decay_mult': 2.0834018998777646, 'trailing_sl': True, 'max_holding_bars': 7}. Best is trial 1 with value: 0.12648941001202754.
[I 2026-03-28 21:41:47,940] Trial 5 finished with value: 0.1738257070953039 and parameters: {'bb_period': 9, 'bb_std': 1.1, 'max_setup_hold_bars': 9, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.2, 'tp_trail_mult': 0.060000000000000005, 'sl_trail_mult': 1.802522143007467, 'time_decay_sl': True, 'time_decay_mult': 2.4607379435418832, 'trailing_sl': True, 'max_holding_bars': 16}. Best is trial 5 with value: 0.1738257070953039.
[I 2026-03-28 21:41:54,268] Trial 6 finished with value: 0.13117589243023445 and parameters: {'bb_period': 5, 'bb_std': 1.5, 'max_setup_hold_bars': 15, 'tp_mult': 1.2, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.05, 'sl_trail_mult': 2.393848014535045, 'time_decay_sl': False, 'time_decay_mult': 2.894427774999036, 'trailing_sl': True, 'max_holding_bars': 13}. Best is trial 5 with value: 0.1738257070953039.
[I 2026-03-28 21:41:59,341] Trial 7 finished with value: 0.38033662974445664 and parameters: {'bb_period': 6, 'bb_std': 2.2, 'max_setup_hold_bars': 6, 'tp_mult': 0.6000000000000001, 'sl_mult': 3.0, 'tp_trail_mult': 0.18000000000000002, 'sl_trail_mult': 3.989521761310952, 'time_decay_sl': True, 'time_decay_mult': 1.9781550848523828, 'trailing_sl': False, 'max_holding_bars': 13}. Best is trial 7 with value: 0.38033662974445664.
[I 2026-03-28 21:42:05,136] Trial 8 finished with value: 0.12456731299272673 and parameters: {'bb_period': 6, 'bb_std': 1.9, 'max_setup_hold_bars': 12, 'tp_mult': 2.0, 'sl_mult': 1.0, 'tp_trail_mult': 0.01, 'sl_trail_mult': 4.141809030268629, 'time_decay_sl': False, 'time_decay_mult': 1.990012031036307, 'trailing_sl': True, 'max_holding_bars': 5}. Best is trial 7 with value: 0.38033662974445664.
[I 2026-03-28 21:42:09,715] Trial 9 finished with value: 0.15778680250956592 and parameters: {'bb_period': 9, 'bb_std': 1.3, 'max_setup_hold_bars': 5, 'tp_mult': 1.6, 'sl_mult': 3.0, 'tp_trail_mult': 0.04, 'sl_trail_mult': 3.6213355819976036, 'time_decay_sl': False, 'time_decay_mult': 0.8822998652901533, 'trailing_sl': False, 'max_holding_bars': 5}. Best is trial 7 with value: 0.38033662974445664.
[I 2026-03-28 21:42:13,867] Trial 10 finished with value: 0.35977668428630394 and parameters: {'bb_period': 18, 'bb_std': 3.2, 'max_setup_hold_bars': 8, 'tp_mult': 0.2, 'sl_mult': 2.2, 'tp_trail_mult': 0.15000000000000002, 'sl_trail_mult': 4.799691846657473, 'time_decay_sl': True, 'time_decay_mult': 1.3686621082278667, 'trailing_sl': False, 'max_holding_bars': 10}. Best is trial 7 with value: 0.38033662974445664.
[I 2026-03-28 21:42:19,644] Trial 11 finished with value: 0.3282400763818948 and parameters: {'bb_period': 19, 'bb_std': 3.3000000000000003, 'max_setup_hold_bars': 8, 'tp_mult': 0.2, 'sl_mult': 2.2, 'tp_trail_mult': 0.15000000000000002, 'sl_trail_mult': 4.937380791822018, 'time_decay_sl': True, 'time_decay_mult': 1.405753903513868, 'trailing_sl': False, 'max_holding_bars': 10}. Best is trial 7 with value: 0.38033662974445664.
[I 2026-03-28 21:42:24,115] Trial 12 finished with value: 0.5350590693041548 and parameters: {'bb_period': 20, 'bb_std': 3.0, 'max_setup_hold_bars': 7, 'tp_mult': 0.2, 'sl_mult': 2.2, 'tp_trail_mult': 0.13, 'sl_trail_mult': 4.841843640272327, 'time_decay_sl': True, 'time_decay_mult': 1.4659073056511287, 'trailing_sl': False, 'max_holding_bars': 11}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:42:28,007] Trial 13 finished with value: 0.32164848588268957 and parameters: {'bb_period': 16, 'bb_std': 2.9000000000000004, 'max_setup_hold_bars': 6, 'tp_mult': 0.8, 'sl_mult': 2.6, 'tp_trail_mult': 0.11, 'sl_trail_mult': 3.173447208232488, 'time_decay_sl': True, 'time_decay_mult': 0.7127144918264832, 'trailing_sl': False, 'max_holding_bars': 12}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:42:32,799] Trial 14 finished with value: 0.0980405908799384 and parameters: {'bb_period': 14, 'bb_std': 2.7, 'max_setup_hold_bars': 7, 'tp_mult': 0.4, 'sl_mult': 2.0, 'tp_trail_mult': 0.09999999999999999, 'sl_trail_mult': 4.529988011815255, 'time_decay_sl': True, 'time_decay_mult': 1.7234544459875243, 'trailing_sl': False, 'max_holding_bars': 12}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:42:37,822] Trial 15 finished with value: 0.0 and parameters: {'bb_period': 20, 'bb_std': 3.9000000000000004, 'max_setup_hold_bars': 11, 'tp_mult': 0.8, 'sl_mult': 3.0, 'tp_trail_mult': 0.14, 'sl_trail_mult': 3.3978501571850956, 'time_decay_sl': True, 'time_decay_mult': 1.1214173356216794, 'trailing_sl': False, 'max_holding_bars': 20}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:42:42,441] Trial 16 finished with value: 0.1896505000040541 and parameters: {'bb_period': 12, 'bb_std': 3.5, 'max_setup_hold_bars': 5, 'tp_mult': 0.2, 'sl_mult': 2.6, 'tp_trail_mult': 0.18000000000000002, 'sl_trail_mult': 4.397801658691358, 'time_decay_sl': True, 'time_decay_mult': 1.7041912116608944, 'trailing_sl': False, 'max_holding_bars': 10}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:42:47,560] Trial 17 finished with value: 0.07965598879192104 and parameters: {'bb_period': 16, 'bb_std': 2.5, 'max_setup_hold_bars': 10, 'tp_mult': 0.6000000000000001, 'sl_mult': 1.8000000000000003, 'tp_trail_mult': 0.12, 'sl_trail_mult': 4.968277506200914, 'time_decay_sl': True, 'time_decay_mult': 0.5474159293201828, 'trailing_sl': False, 'max_holding_bars': 14}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:42:52,694] Trial 18 finished with value: 0.12151358688706511 and parameters: {'bb_period': 18, 'bb_std': 2.9000000000000004, 'max_setup_hold_bars': 7, 'tp_mult': 1.0, 'sl_mult': 2.4, 'tp_trail_mult': 0.09, 'sl_trail_mult': 3.7517034477815745, 'time_decay_sl': True, 'time_decay_mult': 1.637338296764759, 'trailing_sl': False, 'max_holding_bars': 8}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:42:58,337] Trial 19 finished with value: 0.06745968561342451 and parameters: {'bb_period': 11, 'bb_std': 1.6, 'max_setup_hold_bars': 9, 'tp_mult': 0.4, 'sl_mult': 3.0, 'tp_trail_mult': 0.18000000000000002, 'sl_trail_mult': 0.5273170504420617, 'time_decay_sl': True, 'time_decay_mult': 2.285583140558545, 'trailing_sl': False, 'max_holding_bars': 11}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:43:03,121] Trial 20 finished with value: 0.1876506675629816 and parameters: {'bb_period': 8, 'bb_std': 3.6, 'max_setup_hold_bars': 6, 'tp_mult': 1.0, 'sl_mult': 2.0, 'tp_trail_mult': 0.08, 'sl_trail_mult': 2.998254348673263, 'time_decay_sl': True, 'time_decay_mult': 2.8620323328924266, 'trailing_sl': False, 'max_holding_bars': 14}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:43:07,758] Trial 21 finished with value: 0.1442292440707483 and parameters: {'bb_period': 17, 'bb_std': 3.1, 'max_setup_hold_bars': 8, 'tp_mult': 0.2, 'sl_mult': 2.2, 'tp_trail_mult': 0.15000000000000002, 'sl_trail_mult': 4.654347630672928, 'time_decay_sl': True, 'time_decay_mult': 1.4364764103470766, 'trailing_sl': False, 'max_holding_bars': 9}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:43:12,368] Trial 22 finished with value: 0.13798969645734785 and parameters: {'bb_period': 20, 'bb_std': 3.2, 'max_setup_hold_bars': 7, 'tp_mult': 0.2, 'sl_mult': 1.8000000000000003, 'tp_trail_mult': 0.13, 'sl_trail_mult': 4.684919227509403, 'time_decay_sl': True, 'time_decay_mult': 1.2110933891329578, 'trailing_sl': False, 'max_holding_bars': 11}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:43:16,890] Trial 23 finished with value: 0.17685410832990614 and parameters: {'bb_period': 14, 'bb_std': 2.3, 'max_setup_hold_bars': 8, 'tp_mult': 0.4, 'sl_mult': 2.4, 'tp_trail_mult': 0.16, 'sl_trail_mult': 4.0369209926499305, 'time_decay_sl': True, 'time_decay_mult': 1.0351330180908078, 'trailing_sl': False, 'max_holding_bars': 9}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:43:21,851] Trial 24 finished with value: 0.13758754785890703 and parameters: {'bb_period': 18, 'bb_std': 2.7, 'max_setup_hold_bars': 9, 'tp_mult': 0.6000000000000001, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.2, 'sl_trail_mult': 4.925914928149379, 'time_decay_sl': True, 'time_decay_mult': 1.5227928914871913, 'trailing_sl': False, 'max_holding_bars': 13}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:43:26,007] Trial 25 finished with value: 0.0 and parameters: {'bb_period': 19, 'bb_std': 3.6, 'max_setup_hold_bars': 5, 'tp_mult': 0.2, 'sl_mult': 1.2000000000000002, 'tp_trail_mult': 0.17, 'sl_trail_mult': 4.304729105412767, 'time_decay_sl': True, 'time_decay_mult': 1.7997084030880777, 'trailing_sl': False, 'max_holding_bars': 11}. Best is trial 12 with value: 0.5350590693041548.
[I 2026-03-28 21:43:31,026] Trial 26 finished with value: 0.5635986640072244 and parameters: {'bb_period': 18, 'bb_std': 2.8, 'max_setup_hold_bars': 7, 'tp_mult': 0.4, 'sl_mult': 2.0, 'tp_trail_mult': 0.13, 'sl_trail_mult': 3.57486236438349, 'time_decay_sl': True, 'time_decay_mult': 0.9455803305669309, 'trailing_sl': True, 'max_holding_bars': 9}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:43:35,698] Trial 27 finished with value: 0.06733116141679875 and parameters: {'bb_period': 14, 'bb_std': 2.7, 'max_setup_hold_bars': 6, 'tp_mult': 0.4, 'sl_mult': 1.6, 'tp_trail_mult': 0.13, 'sl_trail_mult': 3.496606660334381, 'time_decay_sl': True, 'time_decay_mult': 0.9527473451889138, 'trailing_sl': True, 'max_holding_bars': 7}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:43:40,355] Trial 28 finished with value: 0.0852778491258073 and parameters: {'bb_period': 20, 'bb_std': 2.0, 'max_setup_hold_bars': 7, 'tp_mult': 0.8, 'sl_mult': 0.8, 'tp_trail_mult': 0.08, 'sl_trail_mult': 3.2533218583964456, 'time_decay_sl': True, 'time_decay_mult': 0.7596151512659192, 'trailing_sl': True, 'max_holding_bars': 8}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:43:46,157] Trial 29 finished with value: 0.11050615922241368 and parameters: {'bb_period': 16, 'bb_std': 2.2, 'max_setup_hold_bars': 10, 'tp_mult': 0.6000000000000001, 'sl_mult': 1.6, 'tp_trail_mult': 0.11, 'sl_trail_mult': 2.4514602249900337, 'time_decay_sl': False, 'time_decay_mult': 1.8370390349682273, 'trailing_sl': True, 'max_holding_bars': 15}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:43:51,586] Trial 30 finished with value: 0.12085095621292538 and parameters: {'bb_period': 15, 'bb_std': 1.8, 'max_setup_hold_bars': 5, 'tp_mult': 0.6000000000000001, 'sl_mult': 2.0, 'tp_trail_mult': 0.13, 'sl_trail_mult': 3.855172262229849, 'time_decay_sl': True, 'time_decay_mult': 2.2016165600032185, 'trailing_sl': True, 'max_holding_bars': 14}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:43:56,429] Trial 31 finished with value: 0.40529619777391207 and parameters: {'bb_period': 18, 'bb_std': 3.0, 'max_setup_hold_bars': 8, 'tp_mult': 0.4, 'sl_mult': 2.4, 'tp_trail_mult': 0.16, 'sl_trail_mult': 4.586100121207405, 'time_decay_sl': True, 'time_decay_mult': 1.2396081256693101, 'trailing_sl': False, 'max_holding_bars': 10}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:01,689] Trial 32 finished with value: 0.27050456946612017 and parameters: {'bb_period': 17, 'bb_std': 2.9000000000000004, 'max_setup_hold_bars': 7, 'tp_mult': 0.4, 'sl_mult': 2.4, 'tp_trail_mult': 0.19, 'sl_trail_mult': 4.458683144332824, 'time_decay_sl': True, 'time_decay_mult': 1.2527731189009583, 'trailing_sl': True, 'max_holding_bars': 9}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:06,274] Trial 33 finished with value: 0.38059610387490544 and parameters: {'bb_period': 19, 'bb_std': 2.5, 'max_setup_hold_bars': 6, 'tp_mult': 0.6000000000000001, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.16, 'sl_trail_mult': 2.796915718481771, 'time_decay_sl': True, 'time_decay_mult': 1.5399930179910057, 'trailing_sl': False, 'max_holding_bars': 12}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:11,416] Trial 34 finished with value: 0.3822734715589476 and parameters: {'bb_period': 19, 'bb_std': 2.6, 'max_setup_hold_bars': 8, 'tp_mult': 0.4, 'sl_mult': 2.6, 'tp_trail_mult': 0.16, 'sl_trail_mult': 2.6772717381654894, 'time_decay_sl': False, 'time_decay_mult': 1.575912097631089, 'trailing_sl': True, 'max_holding_bars': 11}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:16,876] Trial 35 finished with value: 0.1530307973884753 and parameters: {'bb_period': 17, 'bb_std': 3.0, 'max_setup_hold_bars': 9, 'tp_mult': 0.4, 'sl_mult': 2.6, 'tp_trail_mult': 0.14, 'sl_trail_mult': 1.6579779652577167, 'time_decay_sl': False, 'time_decay_mult': 1.1517606428442806, 'trailing_sl': True, 'max_holding_bars': 8}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:21,818] Trial 36 finished with value: 0.29960675458657 and parameters: {'bb_period': 19, 'bb_std': 2.7, 'max_setup_hold_bars': 8, 'tp_mult': 2.0, 'sl_mult': 2.4, 'tp_trail_mult': 0.16, 'sl_trail_mult': 1.6963337485325385, 'time_decay_sl': False, 'time_decay_mult': 0.8178309763658738, 'trailing_sl': True, 'max_holding_bars': 6}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:27,094] Trial 37 finished with value: 0.2004513271927217 and parameters: {'bb_period': 20, 'bb_std': 3.4000000000000004, 'max_setup_hold_bars': 11, 'tp_mult': 0.4, 'sl_mult': 2.0, 'tp_trail_mult': 0.12, 'sl_trail_mult': 2.6093110457507764, 'time_decay_sl': False, 'time_decay_mult': 0.5668971193644616, 'trailing_sl': True, 'max_holding_bars': 10}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:33,287] Trial 38 finished with value: 0.11486639866967033 and parameters: {'bb_period': 18, 'bb_std': 2.4000000000000004, 'max_setup_hold_bars': 14, 'tp_mult': 0.8, 'sl_mult': 2.2, 'tp_trail_mult': 0.14, 'sl_trail_mult': 2.077495883899278, 'time_decay_sl': False, 'time_decay_mult': 1.2859062810217865, 'trailing_sl': True, 'max_holding_bars': 11}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:38,431] Trial 39 finished with value: 0.17380893507961018 and parameters: {'bb_period': 17, 'bb_std': 2.5, 'max_setup_hold_bars': 9, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.17, 'sl_trail_mult': 2.9725725300517465, 'time_decay_sl': False, 'time_decay_mult': 1.0147594378893572, 'trailing_sl': True, 'max_holding_bars': 9}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:43,622] Trial 40 finished with value: 0.21931879013522296 and parameters: {'bb_period': 15, 'bb_std': 3.0, 'max_setup_hold_bars': 8, 'tp_mult': 0.2, 'sl_mult': 1.4, 'tp_trail_mult': 0.12, 'sl_trail_mult': 2.0683478666931956, 'time_decay_sl': False, 'time_decay_mult': 1.575707273705051, 'trailing_sl': True, 'max_holding_bars': 17}. Best is trial 26 with value: 0.5635986640072244.
[I 2026-03-28 21:44:48,430] Trial 41 finished with value: 0.6204418790458058 and parameters: {'bb_period': 19, 'bb_std': 2.8, 'max_setup_hold_bars': 6, 'tp_mult': 0.4, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.17, 'sl_trail_mult': 2.6863086483522656, 'time_decay_sl': True, 'time_decay_mult': 1.4526506079599446, 'trailing_sl': False, 'max_holding_bars': 12}. Best is trial 41 with value: 0.6204418790458058.
[I 2026-03-28 21:44:53,664] Trial 42 finished with value: 0.483998746843832 and parameters: {'bb_period': 19, 'bb_std': 2.8, 'max_setup_hold_bars': 7, 'tp_mult': 0.4, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.2, 'sl_trail_mult': 1.1462133205930594, 'time_decay_sl': True, 'time_decay_mult': 1.3930764072165571, 'trailing_sl': True, 'max_holding_bars': 12}. Best is trial 41 with value: 0.6204418790458058.
[I 2026-03-28 21:44:58,472] Trial 43 finished with value: 0.441023140336745 and parameters: {'bb_period': 18, 'bb_std': 2.8, 'max_setup_hold_bars': 7, 'tp_mult': 0.2, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.19, 'sl_trail_mult': 1.3291033920724882, 'time_decay_sl': True, 'time_decay_mult': 1.3532472215856948, 'trailing_sl': False, 'max_holding_bars': 13}. Best is trial 41 with value: 0.6204418790458058.
[I 2026-03-28 21:45:03,261] Trial 44 finished with value: 0.3960227932137498 and parameters: {'bb_period': 20, 'bb_std': 3.2, 'max_setup_hold_bars': 6, 'tp_mult': 0.2, 'sl_mult': 3.0, 'tp_trail_mult': 0.2, 'sl_trail_mult': 1.1893309804781214, 'time_decay_sl': True, 'time_decay_mult': 1.3908071331563379, 'trailing_sl': False, 'max_holding_bars': 15}. Best is trial 41 with value: 0.6204418790458058.
[I 2026-03-28 21:45:08,045] Trial 45 finished with value: 0.4942081314208432 and parameters: {'bb_period': 19, 'bb_std': 2.8, 'max_setup_hold_bars': 7, 'tp_mult': 0.2, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.19, 'sl_trail_mult': 1.3503716641997927, 'time_decay_sl': True, 'time_decay_mult': 1.866577935715056, 'trailing_sl': True, 'max_holding_bars': 13}. Best is trial 41 with value: 0.6204418790458058.
[I 2026-03-28 21:45:13,116] Trial 46 finished with value: 0.30431259213134515 and parameters: {'bb_period': 19, 'bb_std': 2.8, 'max_setup_hold_bars': 6, 'tp_mult': 0.6000000000000001, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.19, 'sl_trail_mult': 0.9959649735140979, 'time_decay_sl': True, 'time_decay_mult': 1.8549404152365603, 'trailing_sl': True, 'max_holding_bars': 12}. Best is trial 41 with value: 0.6204418790458058.
[I 2026-03-28 21:45:18,725] Trial 47 finished with value: 0.19044239897024698 and parameters: {'bb_period': 20, 'bb_std': 3.3000000000000003, 'max_setup_hold_bars': 7, 'tp_mult': 1.6, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.17, 'sl_trail_mult': 1.3316985350328274, 'time_decay_sl': True, 'time_decay_mult': 2.073256337399974, 'trailing_sl': True, 'max_holding_bars': 16}. Best is trial 41 with value: 0.6204418790458058.

Best parameters: {'bb_period': 19, 'bb_std': 2.8, 'max_setup_hold_bars': 6, 'tp_mult': 0.4, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.17, 'sl_trail_mult': 2.6863086483522656, 'time_decay_sl': True, 'time_decay_mult': 1.4526506079599446, 'trailing_sl': False, 'max_holding_bars': 12}
Best value: 0.6204418790458058

### Optuna => ATR

In [10]:
def objective_atr_tbm_direct(trial):
    # Optymalizacja Parametrow ATR
    atr_period = trial.suggest_int("atr_period", 15, 20)
    atr_factor = trial.suggest_float("atr_factor", 2.0, 5.0)
    max_setup_hold_bars = trial.suggest_int("max_setup_hold_bars", 5, 15)

    # Optymalizacja Wyjsc (TBM)
    tp_mult = trial.suggest_float("tp_mult", 0.2, 2.0, step=0.2)
    sl_mult = trial.suggest_float("sl_mult", 0.6, 5.0, step=0.2)
    tp_trail_mult = trial.suggest_float("tp_trail_mult", 0.01, 0.2, step=0.01)
    sl_trail_mult = trial.suggest_float("sl_trail_mult", 0.5, 5.0)
    time_decay_sl = trial.suggest_categorical("time_decay_sl", [True, False])
    time_decay_mult = trial.suggest_float("time_decay_mult", 0.1, 3.0)
    active_trailing_sl =  trial.suggest_categorical("trailing_sl", [True, False])
    max_holding_bars = trial.suggest_int("max_holding_bars", 5, 25)

    atr_tbm_settings = all_settings['strategies']['atr']['tbm_settings']

    # 1. Generowanie wejsc
    entries_df = generate_odbicie_atr_entries(
        signals_df=signals_df,
        market_data_daily=dfs_1d,
        atr_period=atr_period,
        atr_factor=atr_factor,
        enter_on_close=strat_settings.get('enter_on_close', True),
        max_setup_hold_bars=max_setup_hold_bars,
    )

    if entries_df.empty or len(entries_df) < 10:
        return 0.0

    # 2. Ewaluacja TBM
    trds = moving_triple_barrier_labels(
        entries_df=entries_df,
        market_data_daily=dfs_1d,
        tp_mult=tp_mult,
        sl_mult=sl_mult,
        tp_trail_mult=tp_trail_mult,
        max_holding_bars=max_holding_bars,
        time_decay_sl=time_decay_sl,
        time_decay_mult=time_decay_mult,
        active_trailing_sl=active_trailing_sl,
        sl_trail_mult=sl_trail_mult,
        exit_on_close=atr_tbm_settings.get('exit_on_close', True)
    )

    if len(trds) < 10:
        return 0.0

    avg_hold_bars = trds['hold_bars'].mean()
    if avg_hold_bars == 0:
        return 0.0

    avg_return = trds['return_pct'].mean()
    return avg_return / avg_hold_bars  # return_per_bar

'''
study_atr_tbm_direct = optuna.create_study(direction="maximize")
study_atr_tbm_direct.optimize(objective_atr_tbm_direct, n_trials=50)

print("Best parameters:", study_atr_tbm_direct.best_params)
print("Best value:", study_atr_tbm_direct.best_value)

'''

'\nstudy_atr_tbm_direct = optuna.create_study(direction="maximize")\nstudy_atr_tbm_direct.optimize(objective_atr_tbm_direct, n_trials=50)\n\nprint("Best parameters:", study_atr_tbm_direct.best_params)\nprint("Best value:", study_atr_tbm_direct.best_value)\n\n'

### Optuna => base

In [ ]:
def objective_base_tbm_direct(trial):
    # Optymalizacja Parametrow base
    threshold_pct = trial.suggest_float("threshold_pct", 0.05, 0.5)
    max_setup_hold_bars = trial.suggest_int("max_setup_hold_bars", 5, 15)

    # Optymalizacja Wyjsc (TBM)
    tp_mult = trial.suggest_float("tp_mult", 0.2, 2.0, step=0.2)
    sl_mult = trial.suggest_float("sl_mult", 0.6, 3.0, step=0.2)
    tp_trail_mult = trial.suggest_float("tp_trail_mult", 0.01, 0.2, step=0.01)
    sl_trail_mult = trial.suggest_float("sl_trail_mult", 0.5, 5.0)
    time_decay_sl = trial.suggest_categorical("time_decay_sl", [True, False])
    time_decay_mult = trial.suggest_float("time_decay_mult", 0.5, 3.0)
    active_trailing_sl =  trial.suggest_categorical("trailing_sl", [True, False])
    max_holding_bars = trial.suggest_int("max_holding_bars", 5, 20)

    base_tbm_settings = all_settings['strategies']['base']['tbm_settings']

    # 1. Generowanie wejsc
    entries_df = generate_odbicie_entries(
        signals_df=signals_df,
        market_data_daily=dfs_1d,
        threshold_pct=threshold_pct,
        enter_on_close=strat_settings.get('enter_on_close', True),
        max_setup_hold_bars=max_setup_hold_bars,
    )

    if entries_df.empty or len(entries_df) < 10:
        return 0.0

    # 2. Ewaluacja TBM
    trds = moving_triple_barrier_labels(
        entries_df=entries_df,
        market_data_daily=dfs_1d,
        tp_mult=tp_mult,
        sl_mult=sl_mult,
        tp_trail_mult=tp_trail_mult,
        max_holding_bars=max_holding_bars,
        time_decay_sl=time_decay_sl,
        time_decay_mult=time_decay_mult,
        active_trailing_sl=active_trailing_sl,
        sl_trail_mult=sl_trail_mult,
        exit_on_close=base_tbm_settings.get('exit_on_close', True)
    )

    if len(trds) < 10:
        return 0.0

    avg_hold_bars = trds['hold_bars'].mean()
    if avg_hold_bars == 0:
        return 0.0

    avg_return = trds['return_pct'].mean()
    return avg_return / avg_hold_bars  # return_per_bar

'''
study_base_tbm_direct = optuna.create_study(direction="maximize")
study_base_tbm_direct.optimize(objective_base_tbm_direct, n_trials=50)

print("Best parameters:", study_base_tbm_direct.best_params)
print("Best value:", study_base_tbm_direct.best_value)
'''

[I 2026-03-28 21:45:30,437] A new study created in memory with name: no-name-3b8b756a-0402-44c0-9e28-90ad23526d23
[I 2026-03-28 21:45:33,201] Trial 0 finished with value: 0.24956124756814735 and parameters: {'threshold_pct': 0.09212480188183822, 'max_setup_hold_bars': 13, 'tp_mult': 2.0, 'sl_mult': 2.2, 'tp_trail_mult': 0.2, 'sl_trail_mult': 0.5106320314222976, 'time_decay_sl': False, 'time_decay_mult': 1.8655418406012823, 'trailing_sl': True, 'max_holding_bars': 15}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:36,136] Trial 1 finished with value: 0.19430822507462783 and parameters: {'threshold_pct': 0.05494471793874902, 'max_setup_hold_bars': 6, 'tp_mult': 1.2, 'sl_mult': 2.6, 'tp_trail_mult': 0.11, 'sl_trail_mult': 0.569524605580273, 'time_decay_sl': False, 'time_decay_mult': 1.369608562275774, 'trailing_sl': True, 'max_holding_bars': 10}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:38,363] Trial 2 finished with value: 0.16036865462919475 and parameters: {'threshold_pct': 0.17230589428892876, 'max_setup_hold_bars': 8, 'tp_mult': 0.8, 'sl_mult': 0.8, 'tp_trail_mult': 0.18000000000000002, 'sl_trail_mult': 3.642472968435309, 'time_decay_sl': True, 'time_decay_mult': 1.6600382497322195, 'trailing_sl': True, 'max_holding_bars': 9}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:40,892] Trial 3 finished with value: 0.0 and parameters: {'threshold_pct': 0.37041838738025457, 'max_setup_hold_bars': 8, 'tp_mult': 0.2, 'sl_mult': 1.2000000000000002, 'tp_trail_mult': 0.05, 'sl_trail_mult': 4.669581962236774, 'time_decay_sl': False, 'time_decay_mult': 1.4380346542462652, 'trailing_sl': False, 'max_holding_bars': 8}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:44,021] Trial 4 finished with value: 0.0 and parameters: {'threshold_pct': 0.2772772398691358, 'max_setup_hold_bars': 8, 'tp_mult': 0.6000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.09, 'sl_trail_mult': 2.379008566664021, 'time_decay_sl': False, 'time_decay_mult': 1.9550100935305426, 'trailing_sl': True, 'max_holding_bars': 5}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:46,406] Trial 5 finished with value: 0.0 and parameters: {'threshold_pct': 0.27189234034769966, 'max_setup_hold_bars': 11, 'tp_mult': 1.2, 'sl_mult': 1.4, 'tp_trail_mult': 0.03, 'sl_trail_mult': 1.391278279439569, 'time_decay_sl': False, 'time_decay_mult': 2.4337780937300177, 'trailing_sl': True, 'max_holding_bars': 7}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:49,715] Trial 6 finished with value: 0.0 and parameters: {'threshold_pct': 0.2760796830824262, 'max_setup_hold_bars': 8, 'tp_mult': 0.8, 'sl_mult': 2.0, 'tp_trail_mult': 0.15000000000000002, 'sl_trail_mult': 3.23973482453036, 'time_decay_sl': True, 'time_decay_mult': 2.183285413104297, 'trailing_sl': False, 'max_holding_bars': 7}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:52,651] Trial 7 finished with value: 0.0 and parameters: {'threshold_pct': 0.25677649218070225, 'max_setup_hold_bars': 12, 'tp_mult': 1.0, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.08, 'sl_trail_mult': 4.904310591635096, 'time_decay_sl': True, 'time_decay_mult': 1.8902756562201424, 'trailing_sl': True, 'max_holding_bars': 17}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:55,209] Trial 8 finished with value: 0.0 and parameters: {'threshold_pct': 0.38256810007801706, 'max_setup_hold_bars': 6, 'tp_mult': 0.2, 'sl_mult': 2.0, 'tp_trail_mult': 0.09999999999999999, 'sl_trail_mult': 2.8976205760135505, 'time_decay_sl': True, 'time_decay_mult': 0.6197460813055756, 'trailing_sl': True, 'max_holding_bars': 19}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:45:57,588] Trial 9 finished with value: 0.0 and parameters: {'threshold_pct': 0.4628802620202678, 'max_setup_hold_bars': 15, 'tp_mult': 2.0, 'sl_mult': 1.6, 'tp_trail_mult': 0.15000000000000002, 'sl_trail_mult': 3.6727180454128394, 'time_decay_sl': False, 'time_decay_mult': 2.2122413437084285, 'trailing_sl': False, 'max_holding_bars': 18}. Best is trial 0 with value: 0.24956124756814735.
[I 2026-03-28 21:46:01,104] Trial 10 finished with value: 0.2755921234219786 and parameters: {'threshold_pct': 0.05954866028667576, 'max_setup_hold_bars': 14, 'tp_mult': 2.0, 'sl_mult': 2.2, 'tp_trail_mult': 0.2, 'sl_trail_mult': 1.657456312757744, 'time_decay_sl': False, 'time_decay_mult': 2.833548615904778, 'trailing_sl': False, 'max_holding_bars': 14}. Best is trial 10 with value: 0.2755921234219786.
[I 2026-03-28 21:46:04,489] Trial 11 finished with value: 0.26741028538614214 and parameters: {'threshold_pct': 0.07404337093447985, 'max_setup_hold_bars': 14, 'tp_mult': 2.0, 'sl_mult': 2.2, 'tp_trail_mult': 0.2, 'sl_trail_mult': 0.5390527873475577, 'time_decay_sl': False, 'time_decay_mult': 2.82562453336422, 'trailing_sl': False, 'max_holding_bars': 14}. Best is trial 10 with value: 0.2755921234219786.
[I 2026-03-28 21:46:07,645] Trial 12 finished with value: 0.56383235122621 and parameters: {'threshold_pct': 0.13445776337326443, 'max_setup_hold_bars': 15, 'tp_mult': 1.6, 'sl_mult': 2.4, 'tp_trail_mult': 0.2, 'sl_trail_mult': 1.6401105359173704, 'time_decay_sl': False, 'time_decay_mult': 2.9752726527884823, 'trailing_sl': False, 'max_holding_bars': 13}. Best is trial 12 with value: 0.56383235122621.
[I 2026-03-28 21:46:10,968] Trial 13 finished with value: 0.5920003777016307 and parameters: {'threshold_pct': 0.16104618881815502, 'max_setup_hold_bars': 15, 'tp_mult': 1.6, 'sl_mult': 3.0, 'tp_trail_mult': 0.16, 'sl_trail_mult': 1.9014251353433542, 'time_decay_sl': False, 'time_decay_mult': 2.98032601862024, 'trailing_sl': False, 'max_holding_bars': 12}. Best is trial 13 with value: 0.5920003777016307.
[I 2026-03-28 21:46:14,499] Trial 14 finished with value: 0.7094775467762877 and parameters: {'threshold_pct': 0.1635879623188488, 'max_setup_hold_bars': 15, 'tp_mult': 1.6, 'sl_mult': 3.0, 'tp_trail_mult': 0.16, 'sl_trail_mult': 1.937508877473333, 'time_decay_sl': False, 'time_decay_mult': 2.938170926743862, 'trailing_sl': False, 'max_holding_bars': 11}. Best is trial 14 with value: 0.7094775467762877.
[I 2026-03-28 21:46:17,616] Trial 15 finished with value: 0.5443878962216303 and parameters: {'threshold_pct': 0.19262134814409707, 'max_setup_hold_bars': 10, 'tp_mult': 1.6, 'sl_mult': 3.0, 'tp_trail_mult': 0.14, 'sl_trail_mult': 2.259278641326338, 'time_decay_sl': False, 'time_decay_mult': 2.5624712262339138, 'trailing_sl': False, 'max_holding_bars': 11}. Best is trial 14 with value: 0.7094775467762877.
[I 2026-03-28 21:46:20,810] Trial 16 finished with value: 0.5265454543134993 and parameters: {'threshold_pct': 0.21063478701418253, 'max_setup_hold_bars': 13, 'tp_mult': 1.6, 'sl_mult': 3.0, 'tp_trail_mult': 0.17, 'sl_trail_mult': 1.236426203381507, 'time_decay_sl': False, 'time_decay_mult': 2.585640181905769, 'trailing_sl': False, 'max_holding_bars': 11}. Best is trial 14 with value: 0.7094775467762877.
[I 2026-03-28 21:46:23,374] Trial 17 finished with value: 0.4601285900246393 and parameters: {'threshold_pct': 0.13593686818877368, 'max_setup_hold_bars': 10, 'tp_mult': 1.4000000000000001, 'sl_mult': 3.0, 'tp_trail_mult': 0.13, 'sl_trail_mult': 2.1896684624649776, 'time_decay_sl': False, 'time_decay_mult': 1.1525605482975183, 'trailing_sl': False, 'max_holding_bars': 16}. Best is trial 14 with value: 0.7094775467762877.
[I 2026-03-28 21:46:26,944] Trial 18 finished with value: 0.5944244886904066 and parameters: {'threshold_pct': 0.14297509657129354, 'max_setup_hold_bars': 15, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.17, 'sl_trail_mult': 2.0409393587377322, 'time_decay_sl': True, 'time_decay_mult': 2.3190690714581237, 'trailing_sl': False, 'max_holding_bars': 12}. Best is trial 14 with value: 0.7094775467762877.
[I 2026-03-28 21:46:29,886] Trial 19 finished with value: 0.8423869463540896 and parameters: {'threshold_pct': 0.22208512032414665, 'max_setup_hold_bars': 12, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.12, 'sl_trail_mult': 2.735818312293845, 'time_decay_sl': True, 'time_decay_mult': 2.308431729479876, 'trailing_sl': False, 'max_holding_bars': 20}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:32,342] Trial 20 finished with value: 0.10556525157311204 and parameters: {'threshold_pct': 0.21994612941703479, 'max_setup_hold_bars': 12, 'tp_mult': 1.8, 'sl_mult': 1.8000000000000003, 'tp_trail_mult': 0.06999999999999999, 'sl_trail_mult': 2.8051034850456915, 'time_decay_sl': True, 'time_decay_mult': 2.661798630852636, 'trailing_sl': False, 'max_holding_bars': 20}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:35,359] Trial 21 finished with value: 0.39607360446915185 and parameters: {'threshold_pct': 0.1124631662136966, 'max_setup_hold_bars': 14, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.12, 'sl_trail_mult': 2.603787680023733, 'time_decay_sl': True, 'time_decay_mult': 2.2564933089637056, 'trailing_sl': False, 'max_holding_bars': 12}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:37,849] Trial 22 finished with value: 0.47099271476376825 and parameters: {'threshold_pct': 0.23123088487219623, 'max_setup_hold_bars': 13, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.18000000000000002, 'sl_trail_mult': 1.072688071244599, 'time_decay_sl': True, 'time_decay_mult': 2.391135863823984, 'trailing_sl': False, 'max_holding_bars': 10}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:40,369] Trial 23 finished with value: 0.0 and parameters: {'threshold_pct': 0.34050161989732897, 'max_setup_hold_bars': 11, 'tp_mult': 1.0, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.13, 'sl_trail_mult': 3.2138748490001614, 'time_decay_sl': True, 'time_decay_mult': 2.08261178010291, 'trailing_sl': False, 'max_holding_bars': 13}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:42,975] Trial 24 finished with value: 0.6177256123353007 and parameters: {'threshold_pct': 0.16088012169904836, 'max_setup_hold_bars': 15, 'tp_mult': 1.8, 'sl_mult': 2.4, 'tp_trail_mult': 0.01, 'sl_trail_mult': 2.0209730921015883, 'time_decay_sl': True, 'time_decay_mult': 1.6736455251122107, 'trailing_sl': False, 'max_holding_bars': 16}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:45,293] Trial 25 finished with value: 0.0 and parameters: {'threshold_pct': 0.32362395582129355, 'max_setup_hold_bars': 12, 'tp_mult': 1.8, 'sl_mult': 2.4, 'tp_trail_mult': 0.01, 'sl_trail_mult': 3.85966393052769, 'time_decay_sl': True, 'time_decay_mult': 1.6588414601074413, 'trailing_sl': False, 'max_holding_bars': 20}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:47,970] Trial 26 finished with value: 0.38682982711788355 and parameters: {'threshold_pct': 0.1851970465472611, 'max_setup_hold_bars': 14, 'tp_mult': 1.8, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.060000000000000005, 'sl_trail_mult': 2.4813238661575743, 'time_decay_sl': True, 'time_decay_mult': 1.0031611413612795, 'trailing_sl': False, 'max_holding_bars': 18}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:50,307] Trial 27 finished with value: 0.19309218114871857 and parameters: {'threshold_pct': 0.2400750080234118, 'max_setup_hold_bars': 11, 'tp_mult': 1.8, 'sl_mult': 0.6, 'tp_trail_mult': 0.04, 'sl_trail_mult': 3.0580314995770372, 'time_decay_sl': True, 'time_decay_mult': 1.472062446509836, 'trailing_sl': False, 'max_holding_bars': 16}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:52,827] Trial 28 finished with value: 0.5317182791833368 and parameters: {'threshold_pct': 0.10933172615216451, 'max_setup_hold_bars': 9, 'tp_mult': 1.2, 'sl_mult': 2.4, 'tp_trail_mult': 0.02, 'sl_trail_mult': 1.7867248254666388, 'time_decay_sl': True, 'time_decay_mult': 2.7242017624246673, 'trailing_sl': False, 'max_holding_bars': 18}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:55,314] Trial 29 finished with value: 0.0 and parameters: {'threshold_pct': 0.3118236242512332, 'max_setup_hold_bars': 13, 'tp_mult': 1.8, 'sl_mult': 2.2, 'tp_trail_mult': 0.12, 'sl_trail_mult': 0.9520251990500657, 'time_decay_sl': True, 'time_decay_mult': 1.7906753617893016, 'trailing_sl': False, 'max_holding_bars': 15}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:46:57,901] Trial 30 finished with value: 0.43053877770585924 and parameters: {'threshold_pct': 0.1959618026277821, 'max_setup_hold_bars': 13, 'tp_mult': 1.6, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.09999999999999999, 'sl_trail_mult': 1.4068121488130811, 'time_decay_sl': True, 'time_decay_mult': 1.9886775177895577, 'trailing_sl': False, 'max_holding_bars': 16}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:00,626] Trial 31 finished with value: 0.5361100745349006 and parameters: {'threshold_pct': 0.1496224807299007, 'max_setup_hold_bars': 15, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.4, 'tp_trail_mult': 0.16, 'sl_trail_mult': 1.9372162664450578, 'time_decay_sl': True, 'time_decay_mult': 2.4343673517463333, 'trailing_sl': False, 'max_holding_bars': 14}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:03,493] Trial 32 finished with value: 0.44113632647717094 and parameters: {'threshold_pct': 0.0980306026331533, 'max_setup_hold_bars': 15, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.17, 'sl_trail_mult': 2.027615789126618, 'time_decay_sl': True, 'time_decay_mult': 1.6008993940119667, 'trailing_sl': False, 'max_holding_bars': 11}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:05,930] Trial 33 finished with value: 0.444492844850814 and parameters: {'threshold_pct': 0.13476430019471164, 'max_setup_hold_bars': 14, 'tp_mult': 1.2, 'sl_mult': 2.6, 'tp_trail_mult': 0.18000000000000002, 'sl_trail_mult': 2.613325917340238, 'time_decay_sl': True, 'time_decay_mult': 1.092067756348979, 'trailing_sl': False, 'max_holding_bars': 9}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:08,470] Trial 34 finished with value: 0.7303701418671642 and parameters: {'threshold_pct': 0.16548749255439366, 'max_setup_hold_bars': 15, 'tp_mult': 1.6, 'sl_mult': 2.0, 'tp_trail_mult': 0.14, 'sl_trail_mult': 2.200424895188966, 'time_decay_sl': True, 'time_decay_mult': 2.0918090385927517, 'trailing_sl': True, 'max_holding_bars': 15}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:10,850] Trial 35 finished with value: 0.45706801159072175 and parameters: {'threshold_pct': 0.16966760207192444, 'max_setup_hold_bars': 14, 'tp_mult': 1.6, 'sl_mult': 2.0, 'tp_trail_mult': 0.11, 'sl_trail_mult': 2.3180907790668908, 'time_decay_sl': True, 'time_decay_mult': 2.067735073532547, 'trailing_sl': True, 'max_holding_bars': 15}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:12,769] Trial 36 finished with value: 0.0 and parameters: {'threshold_pct': 0.21022016494807572, 'max_setup_hold_bars': 5, 'tp_mult': 1.8, 'sl_mult': 1.8000000000000003, 'tp_trail_mult': 0.13, 'sl_trail_mult': 1.5588897299202271, 'time_decay_sl': True, 'time_decay_mult': 1.8002356228398633, 'trailing_sl': True, 'max_holding_bars': 17}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:15,070] Trial 37 finished with value: 0.0 and parameters: {'threshold_pct': 0.25141003773676707, 'max_setup_hold_bars': 12, 'tp_mult': 2.0, 'sl_mult': 1.2000000000000002, 'tp_trail_mult': 0.09, 'sl_trail_mult': 3.5132992483807137, 'time_decay_sl': False, 'time_decay_mult': 1.2690434698338509, 'trailing_sl': True, 'max_holding_bars': 19}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:17,362] Trial 38 finished with value: 0.2917128719239555 and parameters: {'threshold_pct': 0.17474569945733517, 'max_setup_hold_bars': 9, 'tp_mult': 1.2, 'sl_mult': 1.6, 'tp_trail_mult': 0.14, 'sl_trail_mult': 4.179623938534809, 'time_decay_sl': True, 'time_decay_mult': 1.5226720052564813, 'trailing_sl': True, 'max_holding_bars': 17}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:19,447] Trial 39 finished with value: 0.0 and parameters: {'threshold_pct': 0.2905761041763109, 'max_setup_hold_bars': 7, 'tp_mult': 0.8, 'sl_mult': 2.2, 'tp_trail_mult': 0.12, 'sl_trail_mult': 0.8289714811076083, 'time_decay_sl': True, 'time_decay_mult': 2.081370413294793, 'trailing_sl': True, 'max_holding_bars': 9}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:22,140] Trial 40 finished with value: 0.22437441922765997 and parameters: {'threshold_pct': 0.08298912513981274, 'max_setup_hold_bars': 13, 'tp_mult': 1.6, 'sl_mult': 2.0, 'tp_trail_mult': 0.08, 'sl_trail_mult': 2.797994015081776, 'time_decay_sl': False, 'time_decay_mult': 1.8899474258912967, 'trailing_sl': True, 'max_holding_bars': 19}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:24,828] Trial 41 finished with value: 0.628115809945102 and parameters: {'threshold_pct': 0.1283894298123206, 'max_setup_hold_bars': 15, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.15000000000000002, 'sl_trail_mult': 2.0666385405050756, 'time_decay_sl': True, 'time_decay_mult': 2.3962066160894753, 'trailing_sl': True, 'max_holding_bars': 10}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:27,567] Trial 42 finished with value: 0.5445872252125661 and parameters: {'threshold_pct': 0.1075485071811047, 'max_setup_hold_bars': 15, 'tp_mult': 1.2, 'sl_mult': 2.4, 'tp_trail_mult': 0.15000000000000002, 'sl_trail_mult': 2.178076467324847, 'time_decay_sl': True, 'time_decay_mult': 2.4821552193687113, 'trailing_sl': True, 'max_holding_bars': 8}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:29,822] Trial 43 finished with value: 0.0 and parameters: {'threshold_pct': 0.4880787988736014, 'max_setup_hold_bars': 14, 'tp_mult': 1.0, 'sl_mult': 2.8000000000000003, 'tp_trail_mult': 0.14, 'sl_trail_mult': 2.468433587991582, 'time_decay_sl': True, 'time_decay_mult': 2.19206372762701, 'trailing_sl': True, 'max_holding_bars': 10}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:32,797] Trial 44 finished with value: 0.1258693169964595 and parameters: {'threshold_pct': 0.05005901455094007, 'max_setup_hold_bars': 15, 'tp_mult': 0.4, 'sl_mult': 2.4, 'tp_trail_mult': 0.11, 'sl_trail_mult': 3.0765333247865714, 'time_decay_sl': True, 'time_decay_mult': 2.7995909588408923, 'trailing_sl': True, 'max_holding_bars': 7}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:35,108] Trial 45 finished with value: 0.27946610783422604 and parameters: {'threshold_pct': 0.16004947476044343, 'max_setup_hold_bars': 14, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.2, 'tp_trail_mult': 0.16, 'sl_trail_mult': 1.7696937855511774, 'time_decay_sl': True, 'time_decay_mult': 1.99461901771052, 'trailing_sl': True, 'max_holding_bars': 5}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:37,724] Trial 46 finished with value: 0.3895013434330621 and parameters: {'threshold_pct': 0.12199030478637021, 'max_setup_hold_bars': 15, 'tp_mult': 1.6, 'sl_mult': 2.6, 'tp_trail_mult': 0.15000000000000002, 'sl_trail_mult': 1.4920051925138378, 'time_decay_sl': False, 'time_decay_mult': 2.367480783751148, 'trailing_sl': True, 'max_holding_bars': 14}. Best is trial 19 with value: 0.8423869463540896.
[I 2026-03-28 21:47:40,153] Trial 47 finished with value: 0.47797566287190735 and parameters: {'threshold_pct': 0.19354162809928674, 'max_setup_hold_bars': 13, 'tp_mult': 1.8, 'sl_mult': 3.0, 'tp_trail_mult': 0.19, 'sl_trail_mult': 2.629057239908995, 'time_decay_sl': True, 'time_decay_mult': 2.587907887898442, 'trailing_sl': True, 'max_holding_bars': 15}. Best is trial 19 with value: 0.8423869463540896.

Best parameters: {'threshold_pct': 0.22208512032414665, 'max_setup_hold_bars': 12, 'tp_mult': 1.4000000000000001, 'sl_mult': 2.6, 'tp_trail_mult': 0.12, 'sl_trail_mult': 2.735818312293845, 'time_decay_sl': True, 'time_decay_mult': 2.308431729479876, 'trailing_sl': False, 'max_holding_bars': 20}
Best value: 0.8423869463540896

## Lookup

### Model
Leave-one-out cross-validation of the meta-learning model. Shows how accurately the model predicts each of the 9 TBM parameters from historical data.

In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyArrowPatch

# ─── PREDICTOR SWITCH ───────────────────────────────────────────
# Change 'xgb' to 'mtl' to use the PyTorch neural network instead
PREDICTOR_TYPE = 'mtl'   # 'xgb' | 'mtl'

# ────────────────────────────────────────────────────────────────
LOOKUP_PATH = "cache/lookup/tbm_lookup.json"
STRATEGY    = "base"   # 'base' | 'atr' | 'bb'
DANE_DIR    = "cache"

from odbicie.tbm.predyktor.pred_factory import get_predictor
predictor = get_predictor(PREDICTOR_TYPE, LOOKUP_PATH, STRATEGY, cache_dir=os.path.join(DANE_DIR, 'predyktor'))
print(predictor)


if not predictor.is_ready:
    print(f'Not enough data for strategy={STRATEGY!r} (need >= 15 records). Run tbm_settings_generator first.')
else:
    print(f'Running leave-one-out validation on {len(predictor._records)} records...')
    print('(This may take ~30s depending on dataset size)')
    loo = predictor.leave_one_out_errors()
    print('Done!')

    reg_targets = loo['reg_targets']   # 6 continuous/integer
    cls_targets = loo['cls_targets']   # 2 booleans
    reg_errors  = loo['reg_errors']    # shape (n, 6)
    cls_errors  = loo['cls_errors']    # shape (n, 2)
    Y_reg       = loo['Y_reg']
    Y_cls       = loo['Y_cls']
    n           = loo['n']

    # ── Styling ───────────────────────────────────────────────────────────
    plt.style.use('dark_background')
    ACCENT   = '#7EB8F7'   # blue
    ACCENT2  = '#F7C27E'   # amber
    GOOD     = '#5CDB95'   # green
    BAD      = '#FC4F4F'   # red
    BG       = '#141824'
    PANEL    = '#1E2436'

    # ══════════════════════════════════════════════════════════════════════
    # PLOT 1 — MAE bar chart for all 9 targets
    # ══════════════════════════════════════════════════════════════════════
    fig, ax = plt.subplots(figsize=(13, 5), facecolor=BG)
    ax.set_facecolor(PANEL)

    mae_reg = reg_errors.mean(axis=0)
    mae_cls = cls_errors.mean(axis=0)   # fraction wrong (0-1)

    all_labels = reg_targets + cls_targets
    all_mae    = list(mae_reg) + list(mae_cls)
    colors     = [ACCENT] * len(reg_targets) + [ACCENT2] * len(cls_targets)

    bars = ax.bar(all_labels, all_mae, color=colors, edgecolor='none', width=0.6, zorder=3)
    ax.grid(axis='y', color='white', alpha=0.07, zorder=0)
    ax.set_ylabel('Mean Absolute Error (LOO)', color='white', fontsize=11)
    ax.set_title(f'Predictor Quality — Leave-One-Out MAE per TBM Parameter  |  strategy={STRATEGY!r}  |  n={n}',
                 color='white', fontsize=13, fontweight='bold', pad=12)
    ax.tick_params(colors='white'); ax.spines[:].set_visible(False)
    ax.set_ylim(bottom=0)

    # Value labels on bars
    for bar, val, is_cls in zip(bars, all_mae, [False]*6 + [True]*2):
        label = f'{val:.1%}' if is_cls else f'{val:.3f}'
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + max(all_mae)*0.01,
                label, ha='center', va='bottom', color='white', fontsize=9)

    # Legend patch
    import matplotlib.patches as mpatches
    ax.legend(handles=[
        mpatches.Patch(color=ACCENT,  label='Regression targets (continuous / integer)'),
        mpatches.Patch(color=ACCENT2, label='Classification targets (boolean — shown as error rate)'),
    ], facecolor=BG, edgecolor='none', labelcolor='white', fontsize=9, loc='upper right')

    plt.tight_layout()
    plt.show()

    # ══════════════════════════════════════════════════════════════════════
    # PLOT 2 — Actual vs Predicted scatter for each regression target
    # ══════════════════════════════════════════════════════════════════════
    # Reconstruct LOO predictions from errors (pred = actual - signed_error)
    # We only have absolute errors so we'll display error distribution instead
    ncols = 3
    nrows = 2
    fig2, axes = plt.subplots(nrows, ncols, figsize=(14, 8), facecolor=BG)
    fig2.suptitle(f'LOO Error Distributions — Regression Targets  |  strategy={STRATEGY!r}',
                  color='white', fontsize=13, fontweight='bold', y=1.01)

    for idx, (tgt, errors_col, actuals_col) in enumerate(
            zip(reg_targets, reg_errors.T, Y_reg.T)):
        row, col = divmod(idx, ncols)
        ax2 = axes[row][col]
        ax2.set_facecolor(PANEL)

        # Violin + jitter scatter
        parts = ax2.violinplot(errors_col, positions=[0], widths=0.6,
                               showmedians=True, showextrema=False)
        for pc in parts['bodies']:
            pc.set_facecolor(ACCENT); pc.set_alpha(0.4)
        parts['cmedians'].set_color(GOOD); parts['cmedians'].set_linewidth(2)

        jitter = np.random.uniform(-0.15, 0.15, size=len(errors_col))
        ax2.scatter(jitter, errors_col, color=ACCENT, alpha=0.5, s=18, zorder=3)

        mae_val = errors_col.mean()
        ax2.axhline(mae_val, color=ACCENT2, linestyle='--', linewidth=1.2,
                    label=f'MAE={mae_val:.3f}')

        ax2.set_title(tgt, color='white', fontsize=10, fontweight='bold')
        ax2.set_ylabel('Absolute Error', color='white', fontsize=8)
        ax2.set_xticks([])
        ax2.tick_params(colors='white', labelsize=8)
        ax2.spines[:].set_visible(False)
        ax2.grid(axis='y', color='white', alpha=0.07)
        ax2.legend(facecolor=BG, edgecolor='none', labelcolor='white', fontsize=8)

    plt.tight_layout()
    plt.show()

    # ══════════════════════════════════════════════════════════════════════
    # PLOT 3 — Boolean classification accuracy bars
    # ══════════════════════════════════════════════════════════════════════
    fig3, axes3 = plt.subplots(1, 2, figsize=(9, 4), facecolor=BG)
    fig3.suptitle(f'LOO Boolean Prediction Accuracy  |  strategy={STRATEGY!r}',
                  color='white', fontsize=13, fontweight='bold')

    for idx, (tgt, err_col, actual_col) in enumerate(
            zip(cls_targets, cls_errors.T, Y_cls.T)):
        ax3 = axes3[idx]
        ax3.set_facecolor(PANEL)

        error_rate = err_col.mean()
        accuracy   = 1 - error_rate

        # Stacked bar: accuracy (green) + error (red)
        ax3.bar(['Prediction'], [accuracy], color=GOOD, label=f'Correct ({accuracy:.1%})', width=0.4)
        ax3.bar(['Prediction'], [error_rate], bottom=[accuracy], color=BAD,
                label=f'Wrong ({error_rate:.1%})', width=0.4)

        # Class distribution
        true_rate  = actual_col.mean()
        false_rate = 1 - true_rate
        ax3.bar(['Actual dist.'], [true_rate],  color=ACCENT,  label=f'True  ({true_rate:.1%})',  width=0.4)
        ax3.bar(['Actual dist.'], [false_rate], bottom=[true_rate], color=ACCENT2,
                label=f'False ({false_rate:.1%})', width=0.4)

        ax3.set_title(tgt, color='white', fontsize=11, fontweight='bold')
        ax3.set_ylim(0, 1.05)
        ax3.set_ylabel('Fraction', color='white')
        ax3.tick_params(colors='white'); ax3.spines[:].set_visible(False)
        ax3.grid(axis='y', color='white', alpha=0.07)
        ax3.legend(facecolor=BG, edgecolor='none', labelcolor='white', fontsize=8, loc='lower right')

    plt.tight_layout()
    plt.show()

    # ══════════════════════════════════════════════════════════════════════
    # PLOT 4 — Error heatmap (records × targets)
    # ══════════════════════════════════════════════════════════════════════
    # Normalise each column by its mean so all targets are on the same 0-3 scale
    reg_norm = reg_errors / (reg_errors.mean(axis=0) + 1e-9)
    cls_norm = cls_errors.astype(float)          # already 0/1
    heat     = np.hstack([reg_norm, cls_norm])

    fig4, ax4 = plt.subplots(figsize=(13, max(4, n * 0.18 + 1)), facecolor=BG)
    ax4.set_facecolor(BG)

    im = ax4.imshow(heat, aspect='auto', cmap='RdYlGn_r', vmin=0, vmax=2.5,
                    interpolation='nearest')

    ax4.set_xticks(range(len(all_labels)))
    ax4.set_xticklabels(all_labels, rotation=30, ha='right', color='white', fontsize=9)
    ax4.set_yticks([])
    ax4.set_ylabel(f'Records (n={n})', color='white', fontsize=10)
    ax4.set_title(
        f'LOO Error Heatmap (normalised per column)  |  strategy={STRATEGY!r}\n'
        'Green = easy to predict  |  Red = hard to predict',
        color='white', fontsize=12, fontweight='bold', pad=10)
    ax4.spines[:].set_visible(False)

    cbar = fig4.colorbar(im, ax=ax4, shrink=0.6, pad=0.02)
    cbar.ax.tick_params(colors='white')
    cbar.set_label('Normalised error (1 = MAE)', color='white', fontsize=9)

    plt.tight_layout()
    plt.show()

    # ── Summary stats —————————————————————————————————————————————
    print('\n── LOO Summary ──────────────────────────────────────────────────')
    print(f'{"Target":<20} {"MAE":>10} {"Median AE":>12} {"Max AE":>10}')
    print('-' * 55)
    for tgt, errs in zip(reg_targets, reg_errors.T):
        print(f'{tgt:<20} {errs.mean():>10.4f} {np.median(errs):>12.4f} {errs.max():>10.4f}')
    for tgt, errs in zip(cls_targets, cls_errors.T):
        accuracy = 1 - errs.mean()
        print(f'{tgt:<20} {"accuracy":>10}  {accuracy:>11.1%}')

ModuleNotFoundError: No module named 'tbm.tbm_predictor_factory'

### Comparison

In [29]:
import pandas as pd
import os
import json
from odbicie.tbm.predyktor.pred_factory import get_predictor

# 1. Manually resolve paths to be safe
# We assume you are running inside 'odbicie' folder or project root
CWD = os.getcwd()
BASE_DIR = CWD if os.path.basename(CWD) == 'odbicie' else os.path.join(CWD, 'odbicie')
CACHE_DIR = os.path.join(BASE_DIR, 'cache')
LOOKUP_PATH = os.path.join(CACHE_DIR, 'lookup', 'tbm_lookup.json')
SETTINGS_PATH = os.path.join(BASE_DIR, 'settings.json')

# 2. Load settings and choose STRATEGY
with open(SETTINGS_PATH, 'r') as f:
    all_settings = json.load(f)

# Choose strategy ('bb', 'atr', or 'base')
CURRENT_STRAT = 'base' 
strat_settings = all_settings['strategies'][CURRENT_STRAT]['entry_settings']

# 3. Setup Parameters for the test
if CURRENT_STRAT == 'bb':
    entry_params = {
        'bb_period': strat_settings['bb_period'],
        'bb_std': strat_settings['bb_std'],
        'max_setup_hold_bars': strat_settings['max_setup_hold_bars']
    }
elif CURRENT_STRAT == 'atr':
    entry_params = {
        'atr_period': strat_settings['atr_period'],
        'atr_factor': strat_settings['atr_factor'],
        'max_setup_hold_bars': strat_settings['max_setup_hold_bars']
    }
else:
    entry_params = {
        'threshold_pct': strat_settings['threshold_pct'],
        'max_setup_hold_bars': strat_settings['max_setup_hold_bars']
    }

context_features = {'avg_rsi_at_entry': 30.0, 'avg_atr_pct': 0.02, 'avg_setup_bars': 5.0, 'entry_count_log': 3.0}

# 4. Get Predictions and Optuna Match
results = {}
for ptype in ['xgb', 'mtl']:
    pred = get_predictor(ptype, LOOKUP_PATH, CURRENT_STRAT, cache_dir=os.path.join(CACHE_DIR, 'predyktor'))
    name = ptype.upper()
    if pred.is_ready:
        results[name] = pred.predict(entry_params, context_features)
    else:
        results[name] = {k: f"Need {15 - len(pred._records)} more records" for k in ["tp_mult", "sl_mult"]}

# Try finding Optuna Match
tmp_pred = get_predictor('xgb', LOOKUP_PATH, CURRENT_STRAT, cache_dir=os.path.join(CACHE_DIR, 'predyktor'))
neighbors = tmp_pred.knn_neighbors(entry_params, k=1)
if neighbors and neighbors[0]['distance'] < 1e-5:
    results['OPTUNA (Actual)'] = neighbors[0]['tbm_params']
else:
    results['OPTUNA (Actual)'] = {k: "No direct match" for k in ["tp_mult", "sl_mult"]}

# 5. Output
print(f"Comparing Predictors for strategy: {CURRENT_STRAT}")
display(pd.DataFrame.from_dict(results))

[TbmPredictor] Trained on 174 records for strategy='base' (6 features -> 6 reg + 2 cls targets)
[TbmPredictorMTL] Trained on 174 records for strategy='base' (6 features -> 6 reg + 2 cls heads)
Comparing Predictors for strategy: base

                       XGB       MTL OPTUNA (Actual)
tp_mult            2.30117  1.178531             4.4
sl_mult           5.887368  6.261729             7.4
tp_trail_mult     0.278684  0.148775            0.56
sl_trail_mult     3.249779  5.920358             9.2
time_decay_mult   4.165958  3.685022             4.7
max_holding_bars         6        21               5
active_trail_sl      False      True            True
time_decay_sl        False     False           False
exit_on_close         True      True            True